name: create-ecr
description: Plugin managing creation of AWS ECR
author: https://github.com/seek-oss
requirements:
  - docker
configuration:
  properties:
    name:
      type: string
    permissions-policy:
      type: string
    lifecycle-policy:
      type: string
  required: ["name"]
